lname: Cleanup API Document Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          PR_DIR="pr-${{ github.event.pull_request.number }}"
          if [ -d "$PR_DIR" ]; then
            rm -rf "$PR_DIR"
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}"
            git push
          fi
